### ISSUE TITLE
Repository에서 NetworkService 의 UserInfo 가 필요합니다.

### ISSUE THREAD

**Issue by devaspirant0510** [tjrkdgnl/Algorithm_Management_App#32]
현재 Repository에서 getUserInfo 를 하면 
```kotlin
    override suspend fun getUserInfo(userId: String): UserInfo? {
        return mFirebaseService.getUserInfo(userId)
    }

```
파이어베이스 서비스를 통해 가져오는데 
```kotlin
data class UserInfo(
    val userId :String,
    val userPw: String,
    val fcmToken :String?
){
    constructor() :this("","","")
}
```
UserInfo 에는 사용자 아이디,비번,토큰 이렇게 3가지를 리턴해줍니다.
그러나 메인화면에서 drawer navigation 에 유저정보를 보여줄때 티어이미지가 필요합니다.
![image](https://user-images.githubusercontent.com/68223593/154620729-b3045d26-d20b-486e-bc81-78aedbcc2da7.png)
[https://solved.ac/api/v3/user/show](https://solvedac.github.io/unofficial-documentation/#/operations/getUser) 해당 solved API 에서 더 자세한 유저정보( 티어,전체등수,프로필사진,닉네임 등) 다양한 정보가 담겨져있고 추후 앱을 확장한다했을때 여기있는정보들을 더 활용할수 있을것같습니다.
![image](https://user-images.githubusercontent.com/68223593/154621641-6cdec152-52cd-4fba-947a-e51f277c2664.png)
또한 kakao oven 에는 안써져있는것같은데 ViewProblem 에서 각 댓글의 프로필사진을 티어 이미지로 하자고 했던것같아 NetworkService 를 통해 UserInfo를 가져오는 API가 필요할것같습니다.

**Comment by tjrkdgnl** [comment]
```Kotlin


interface KAPIService {
   ...

    @GET("user/show")
    suspend fun getUserInfo(@Query("handle") userId: String): User

}

class Repository : BaseRepository {
   
    ...
   
    override suspend fun getBOJUserInfo(): User {
        if (mUserId ==null) {
            throw NullPointerException(mApp.getString(R.string.objectIsNull, "mUserId"))
        }

        return mNetworkService.getUserInfo(mUserId!!)
    }

}


```

- Repository에서 getBOJUserInfo()를 호출하는 방식으로 말씀하셨던 정보를 가져올 수 있게 추가했습니다.
